### ISSUE TITLE
script computepitch

### ISSUE THREAD

**Issue by desothier1** [alexanderlerch/pyACA#3]
Dear Professor Lerch,

I used one of your scripts, 
computepitch, in order to list F0 values and time stamps,

Would it be possible that for values that should be zero, or in Praat tool 'undefined', extremely high values are generated. Do you have an idea, what the issue is ?

Thanks

Best regards

**Comment by alexanderlerch** [comment]
Hi, 
and yes, that's absolutely possible. The reason is that the goal for my scripts are really to show an algorithm rather than provide a practically usable implementation. They are intended for you to understand the algorithm, so they do not deal with prudent extra processing.

As for when the output should be undefined, this is mostly if
1. the input energy is very low (e.g., no useful tonal signal but low amplitude noise)
2. the input signal is noise like (e.g., singer singing shshshsh/inhaling)
3. more than one input pitch is available (e.g., in a reverberant environment).
While there is no easy remedy for the latter but changing the pitch detection algorithm, you can deal with the first two scenarios by a combination of allowed conditions and pre- as well as post-processing steps. This might include
- pre-processing: don't do pitch detection of low-energy frames
- processing: check the confidence measure of the pitch estimate (in the case of ACF, maybe the height of the maximum) and don't report values with low confidence
- post-processing: detect unusual values or trajectories - if the detected fundamental frequency jumps from block to block erratically and/or has extreme values, most likely your input signal is not tonal and you can ignore these results.

Of course, there are plenty of other options to optimize and tweak your algorithm, and their success also depends on the what the typical input signal is in your case.

Hope that helps,
Alexander
